#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_depth_call() works", {

  expect_error(
    kwb.code:::get_depth_call()
    # argument "x" is missing, with no default
  )

})

