#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("expressions_stat() works", {

  expect_error(
    kwb.code:::expressions_stat()
    # argument "x" is missing, with no default
  )

})

