#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("removeAttribute() works", {

  expect_error(
    kwb.code:::removeAttribute()
    # argument "x" is missing, with no default
  )

})

