#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("split_assignment() works", {

  expect_error(
    kwb.code:::split_assignment()
    # argument "assignment" is missing, with no default
  )

})

