#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("expressions_by_class() works", {

  expect_error(
    kwb.code:::expressions_by_class()
    # argument "tree" is missing, with no default
  )

})

