#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("expressions_per_function() works", {

  expect_error(
    kwb.code:::expressions_per_function()
    # argument "functionInfo" is missing, with no default
  )

})

