#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("split_function_def_call() works", {

  expect_error(
    kwb.code:::split_function_def_call()
    # argument "functionCall" is missing, with no default
  )

})

