#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to_full_script_info() works", {

  expect_error(
    kwb.code:::to_full_script_info()
    # argument "trees" is missing, with no default
  )

})

