#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("writeContentToFile() works", {

  expect_error(
    kwb.code:::writeContentToFile()
    # argument "file" is missing, with no default
  )

})

