#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("count_functions() works", {

  expect_error(
    kwb.code:::count_functions()
    # argument "trees" is missing, with no default
  )

})

