#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("trees_to_script_info() works", {

  expect_error(
    kwb.code:::trees_to_script_info()
    # argument "x" is missing, with no default
  )

})

