#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("is_assignment() works", {

  expect_error(
    kwb.code:::is_assignment()
    # argument "x" is missing, with no default
  )

})

