#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_depth_assignment() works", {

  expect_error(
    kwb.code:::get_depth_assignment()
    # argument "a" is missing, with no default
  )

})

