#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("normaliseFunction() works", {

  expect_error(
    kwb.code:::normaliseFunction()
    # argument "x" is missing, with no default
  )

})

