#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("merge_function_info() works", {

  expect_error(
    kwb.code:::merge_function_info()
    # argument "functionInfo" is missing, with no default
  )

})

