#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("trees_to_type_stat() works", {

  expect_error(
    kwb.code:::trees_to_type_stat()
    # argument "trees" is missing, with no default
  )

})

