#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_depth() works", {

  expect_error(
    kwb.code:::get_depth()
    # argument "e" is missing, with no default
  )

})

