#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("normalNames() works", {

  expect_error(
    kwb.code:::normalNames()
    # argument "n" is missing, with no default
  )

})

