#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2021-11-27 17:51:47.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("arg_names() works", {

  expect_error(
    kwb.code:::arg_names()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

