#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2021-11-27 17:51:43.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_string_constants_in_scripts() works", {

  expect_error(
    kwb.code:::get_string_constants_in_scripts()
    # Argument "root" fehlt (ohne Standardwert)
  )

})

