#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("targetFile() works", {

  expect_error(
    kwb.code:::targetFile()
    # argument "targetDir" is missing, with no default
  )

})

