#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extract_function_definition() works", {

  expect_error(
    kwb.code:::extract_function_definition()
    # argument "tree" is missing, with no default
  )

})

