#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2021-11-27 17:51:42.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("remove_non_installed_packages() works", {

  expect_error(
    kwb.code:::remove_non_installed_packages()
    # Argument "packages" fehlt (ohne Standardwert)
  )

})

