#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("writeContentsToFiles() works", {

  expect_error(
    kwb.code:::writeContentsToFiles()
    # argument "contents" is missing, with no default
  )

})

