#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("duplicatesToFiles() works", {

  expect_error(
    kwb.code:::duplicatesToFiles()
    # argument "fun_duplicates" is missing, with no default
  )

})

