#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_names_of_used_packages() works", {

  expect_error(
    kwb.code:::get_names_of_used_packages()
    # argument "root_dir" is missing, with no default
  )

})

