#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("replaceNames() works", {

  expect_error(
    kwb.code:::replaceNames()
    # argument "expr" is missing, with no default
  )

})

