#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("filter_scripts() works", {

  expect_error(
    kwb.code:::filter_scripts()
    # argument "scriptInfo" is missing, with no default
  )

})

