#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getNewPairlist() works", {

  expect_error(
    kwb.code:::getNewPairlist()
    # argument "x" is missing, with no default
  )

})

