#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_functions() works", {

  expect_error(
    kwb.code:::get_functions()
    # argument "tree" is missing, with no default
  )

})

