#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("multi_defined_functions() works", {

  expect_error(
    kwb.code:::multi_defined_functions()
    # argument "functionInfo" is missing, with no default
  )

})

