#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("print_elements_with_modes() works", {

  expect_error(
    kwb.code:::print_elements_with_modes()
    # argument "x" is missing, with no default
  )

})

