#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_function_info() works", {

  expect_error(
    kwb.code:::get_function_info()
    # argument "f" is missing, with no default
  )

})

