#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("parse_scripts() works", {

  expect_error(
    kwb.code:::parse_scripts()
    # argument "root" is missing, with no default
  )

})

