#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("split_for() works", {

  expect_error(
    kwb.code:::split_for()
    # argument "x" is missing, with no default
  )

})

