#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("is_function_def_call() works", {

  expect_error(
    kwb.code:::is_function_def_call()
    # argument "x" is missing, with no default
  )

})

