#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("filter_for() works", {

  expect_error(
    kwb.code:::filter_for()
    # argument "FUN.filter" is missing, with no default
  )

})

