#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("split_function_assignment() works", {

  expect_error(
    kwb.code:::split_function_assignment()
    # argument "f" is missing, with no default
  )

})

